//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StampCollectorApp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StampCollectorApp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em caso de ainda não ter registado o selo recebido, faça-o agora, por favor..
        /// </summary>
        internal static string MensagemAposTroca {
            get {
                return ResourceManager.GetString("MensagemAposTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar apenas para Trocas.
        /// </summary>
        internal static string MostrarApenasParaTroca {
            get {
                return ResourceManager.GetString("MostrarApenasParaTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        internal static string TituloAlerta {
            get {
                return ResourceManager.GetString("TituloAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano.
        /// </summary>
        internal static string TituloAno {
            get {
                return ResourceManager.GetString("TituloAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        internal static string TituloApagar {
            get {
                return ResourceManager.GetString("TituloApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Categoria.
        /// </summary>
        internal static string TituloApagarCategoria {
            get {
                return ResourceManager.GetString("TituloApagarCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagando esta Categoria, também apagará todos os selos da mesma. Tem a certeza?.
        /// </summary>
        internal static string TituloApagarCategoriaCaption {
            get {
                return ResourceManager.GetString("TituloApagarCategoriaCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Coleção.
        /// </summary>
        internal static string TituloApagarColecao {
            get {
                return ResourceManager.GetString("TituloApagarColecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagando esta Coleção, também apagará todos os selos da mesma. Tem a certeza?.
        /// </summary>
        internal static string TituloApagarColecaoCaption {
            get {
                return ResourceManager.GetString("TituloApagarColecaoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar País.
        /// </summary>
        internal static string TituloApagarPais {
            get {
                return ResourceManager.GetString("TituloApagarPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagando este País, também apagará todos os selos do mesmo. Tem a certeza?.
        /// </summary>
        internal static string TituloApagarPaisCaption {
            get {
                return ResourceManager.GetString("TituloApagarPaisCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Selo.
        /// </summary>
        internal static string TituloApagarSelo {
            get {
                return ResourceManager.GetString("TituloApagarSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma operação?.
        /// </summary>
        internal static string TituloApagarSeloCaption {
            get {
                return ResourceManager.GetString("TituloApagarSeloCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar filtros.
        /// </summary>
        internal static string TituloAplicarFiltros {
            get {
                return ResourceManager.GetString("TituloAplicarFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string TituloCancelar {
            get {
                return ResourceManager.GetString("TituloCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria.
        /// </summary>
        internal static string TituloCategoria {
            get {
                return ResourceManager.GetString("TituloCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria já existe.
        /// </summary>
        internal static string TituloCategoriaJaExiste {
            get {
                return ResourceManager.GetString("TituloCategoriaJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorias.
        /// </summary>
        internal static string TituloCategorias {
            get {
                return ResourceManager.GetString("TituloCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção.
        /// </summary>
        internal static string TituloColecao {
            get {
                return ResourceManager.GetString("TituloColecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção completa.
        /// </summary>
        internal static string TituloColecaoCompleta {
            get {
                return ResourceManager.GetString("TituloColecaoCompleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coleção já está completa. Deseja criar este selo como &apos;Para Troca&apos;?.
        /// </summary>
        internal static string TituloColecaoCompletaCaption {
            get {
                return ResourceManager.GetString("TituloColecaoCompletaCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome da Coleção é requerido.
        /// </summary>
        internal static string TituloColecaoVazio {
            get {
                return ResourceManager.GetString("TituloColecaoVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleções.
        /// </summary>
        internal static string TituloColecoes {
            get {
                return ResourceManager.GetString("TituloColecoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição.
        /// </summary>
        internal static string TituloCondicao {
            get {
                return ResourceManager.GetString("TituloCondicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto (email/telefone).
        /// </summary>
        internal static string TituloContacto {
            get {
                return ResourceManager.GetString("TituloContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criada em.
        /// </summary>
        internal static string TituloCriadoEm {
            get {
                return ResourceManager.GetString("TituloCriadoEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar / Editar.
        /// </summary>
        internal static string TituloCriarEditarSelo {
            get {
                return ResourceManager.GetString("TituloCriarEditarSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquisição.
        /// </summary>
        internal static string TituloDataAquisicao {
            get {
                return ResourceManager.GetString("TituloDataAquisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data do movimento.
        /// </summary>
        internal static string TituloDataTroca {
            get {
                return ResourceManager.GetString("TituloDataTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string TituloDescricao {
            get {
                return ResourceManager.GetString("TituloDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do selo.
        /// </summary>
        internal static string TituloDescricaoSelo {
            get {
                return ResourceManager.GetString("TituloDescricaoSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string TituloEditar {
            get {
                return ResourceManager.GetString("TituloEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha o idioma.
        /// </summary>
        internal static string TituloEscolherIdioma {
            get {
                return ResourceManager.GetString("TituloEscolherIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha imagem local.
        /// </summary>
        internal static string TituloEscolherImagemLocal {
            get {
                return ResourceManager.GetString("TituloEscolherImagemLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string TituloEstado {
            get {
                return ResourceManager.GetString("TituloEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        internal static string TituloFiltros {
            get {
                return ResourceManager.GetString("TituloFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        internal static string TituloGravar {
            get {
                return ResourceManager.GetString("TituloGravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico de trocas.
        /// </summary>
        internal static string TituloHistoricoTrocas {
            get {
                return ResourceManager.GetString("TituloHistoricoTrocas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informações do colecionador.
        /// </summary>
        internal static string TituloInformacoesColecionador {
            get {
                return ResourceManager.GetString("TituloInformacoesColecionador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar filtros.
        /// </summary>
        internal static string TituloLimparFiltros {
            get {
                return ResourceManager.GetString("TituloLimparFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização.
        /// </summary>
        internal static string TituloLocalizacao {
            get {
                return ResourceManager.GetString("TituloLocalizacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mais....
        /// </summary>
        internal static string TituloMais {
            get {
                return ResourceManager.GetString("TituloMais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar todos...
        /// </summary>
        internal static string TituloMostrarTodos {
            get {
                return ResourceManager.GetString("TituloMostrarTodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string TituloNao {
            get {
                return ResourceManager.GetString("TituloNao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        internal static string TituloNome {
            get {
                return ResourceManager.GetString("TituloNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Coleção.
        /// </summary>
        internal static string TituloNomeColecao {
            get {
                return ResourceManager.GetString("TituloNomeColecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string TituloNotas {
            get {
                return ResourceManager.GetString("TituloNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        internal static string TituloNovo {
            get {
                return ResourceManager.GetString("TituloNovo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso.
        /// </summary>
        internal static string TituloOperacaoComSucess {
            get {
                return ResourceManager.GetString("TituloOperacaoComSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paises.
        /// </summary>
        internal static string TituloPaginaPaises {
            get {
                return ResourceManager.GetString("TituloPaginaPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coleção de Selos.
        /// </summary>
        internal static string TituloPaginaSelos {
            get {
                return ResourceManager.GetString("TituloPaginaSelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string TituloPaises {
            get {
                return ResourceManager.GetString("TituloPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do País já existe.
        /// </summary>
        internal static string TituloPaisJaExiste {
            get {
                return ResourceManager.GetString("TituloPaisJaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Paós  ´requerido.
        /// </summary>
        internal static string TituloPaisVazio {
            get {
                return ResourceManager.GetString("TituloPaisVazio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para troca.
        /// </summary>
        internal static string TituloParaTroca {
            get {
                return ResourceManager.GetString("TituloParaTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar....
        /// </summary>
        internal static string TituloPesquisarSelo {
            get {
                return ResourceManager.GetString("TituloPesquisarSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registar Troca.
        /// </summary>
        internal static string TituloRegistarTroca {
            get {
                return ResourceManager.GetString("TituloRegistarTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha imagem.
        /// </summary>
        internal static string TituloSelecaoImagem {
            get {
                return ResourceManager.GetString("TituloSelecaoImagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selos.
        /// </summary>
        internal static string TituloSelos {
            get {
                return ResourceManager.GetString("TituloSelos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selos disponíveis para troca.
        /// </summary>
        internal static string TituloSelosDisponiveisParaTroca {
            get {
                return ResourceManager.GetString("TituloSelosDisponiveisParaTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selos por Categoria.
        /// </summary>
        internal static string TituloSelosPorCategoria {
            get {
                return ResourceManager.GetString("TituloSelosPorCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selos por Coleção.
        /// </summary>
        internal static string TituloSelosPorColecao {
            get {
                return ResourceManager.GetString("TituloSelosPorColecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selos por País.
        /// </summary>
        internal static string TituloSelosPorPais {
            get {
                return ResourceManager.GetString("TituloSelosPorPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem dados para mostrar.
        /// </summary>
        internal static string TituloSemDados {
            get {
                return ResourceManager.GetString("TituloSemDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há selos disponíveis para troca.
        /// </summary>
        internal static string TituloSemSelosParaTroca {
            get {
                return ResourceManager.GetString("TituloSemSelosParaTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string TituloSim {
            get {
                return ResourceManager.GetString("TituloSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situação.
        /// </summary>
        internal static string TituloSituacao {
            get {
                return ResourceManager.GetString("TituloSituacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Colecionado.
        /// </summary>
        internal static string TituloTotalColecionado {
            get {
                return ResourceManager.GetString("TituloTotalColecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Esperado.
        /// </summary>
        internal static string TituloTotalEsperado {
            get {
                return ResourceManager.GetString("TituloTotalEsperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocas.
        /// </summary>
        internal static string TituloTrocas {
            get {
                return ResourceManager.GetString("TituloTrocas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocas por mês (últimos 12 meses).
        /// </summary>
        internal static string TituloTrocasPorMes {
            get {
                return ResourceManager.GetString("TituloTrocasPorMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validação.
        /// </summary>
        internal static string TituloValidacao {
            get {
                return ResourceManager.GetString("TituloValidacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Ano deverá estar entre 1700 e .
        /// </summary>
        internal static string TituloValidacaoAno {
            get {
                return ResourceManager.GetString("TituloValidacaoAno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de aquisição não pode ser no futuro.
        /// </summary>
        internal static string TituloValidacaoAquisicao {
            get {
                return ResourceManager.GetString("TituloValidacaoAquisicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha Categoria.
        /// </summary>
        internal static string TituloValidacaoCategoria {
            get {
                return ResourceManager.GetString("TituloValidacaoCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha Coleção.
        /// </summary>
        internal static string TituloValidacaoColecao {
            get {
                return ResourceManager.GetString("TituloValidacaoColecao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Colecionado deve ser &lt;= Total Esperado..
        /// </summary>
        internal static string TituloValidacaoColecionado {
            get {
                return ResourceManager.GetString("TituloValidacaoColecionado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve preencher Contacto do Colecionador.
        /// </summary>
        internal static string TituloValidacaoContactoColecionador {
            get {
                return ResourceManager.GetString("TituloValidacaoContactoColecionador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data do movimento não pode ser no futuro.
        /// </summary>
        internal static string TituloValidacaoDataTroca {
            get {
                return ResourceManager.GetString("TituloValidacaoDataTroca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma imagem para o selo.
        /// </summary>
        internal static string TituloValidacaoImagemSelo {
            get {
                return ResourceManager.GetString("TituloValidacaoImagemSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve preencher Nome do Colecionador.
        /// </summary>
        internal static string TituloValidacaoNomeColecionador {
            get {
                return ResourceManager.GetString("TituloValidacaoNomeColecionador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preencha Nome para o selo.
        /// </summary>
        internal static string TituloValidacaoNomeSelo {
            get {
                return ResourceManager.GetString("TituloValidacaoNomeSelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha País.
        /// </summary>
        internal static string TituloValidacaoPais {
            get {
                return ResourceManager.GetString("TituloValidacaoPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Esperado deve ser um valor positivo.
        /// </summary>
        internal static string TituloValidacaoTotalEsperado {
            get {
                return ResourceManager.GetString("TituloValidacaoTotalEsperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor facial.
        /// </summary>
        internal static string TituloValorFacial {
            get {
                return ResourceManager.GetString("TituloValorFacial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor pago.
        /// </summary>
        internal static string TituloValorPago {
            get {
                return ResourceManager.GetString("TituloValorPago", resourceCulture);
            }
        }
    }
}
